// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
package com.tms.vsc.pcps.test.client.scaffold.gae;

import com.google.gwt.event.shared.EventBus;
import com.google.inject.Inject;
import com.tms.vsc.pcps.test.client.managed.request.ApplicationRequestFactory;
import com.tms.vsc.pcps.test.client.scaffold.ScaffoldDesktopShell;

public class GaeHelper {

	@Inject
	public GaeHelper(ScaffoldDesktopShell shell, ApplicationRequestFactory requestFactory, EventBus eventBus) {
		
	}
}