// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.tms.vsc.pcps.test.client.managed.request;

import com.tms.vsc.pcps.test.client.request.TimerRequest;
import com.tms.vsc.pcps.test.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    TimerRequest timerRequest();
}
