// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.tms.vsc.pcps.test.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import com.tms.vsc.pcps.test.client.managed.request.ApplicationEntityTypesProcessor;
import com.tms.vsc.pcps.test.client.managed.request.ApplicationRequestFactory;
import com.tms.vsc.pcps.test.client.managed.ui.TimerListView;
import com.tms.vsc.pcps.test.client.managed.ui.TimerMobileListView;
import com.tms.vsc.pcps.test.client.proxy.TimerProxy;
import com.tms.vsc.pcps.test.client.scaffold.ScaffoldApp;
import com.tms.vsc.pcps.test.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleTimer(TimerProxy isNull) {
                setResult(new TimerListActivity(requests, ScaffoldApp.isMobile() ? TimerMobileListView.instance() : TimerListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
