// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.tms.vsc.pcps.test.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.tms.vsc.pcps.test.client.managed.request.ApplicationRequestFactory;
import com.tms.vsc.pcps.test.client.managed.ui.TimerDetailsView;
import com.tms.vsc.pcps.test.client.managed.ui.TimerEditView;
import com.tms.vsc.pcps.test.client.managed.ui.TimerListView;
import com.tms.vsc.pcps.test.client.managed.ui.TimerMobileDetailsView;
import com.tms.vsc.pcps.test.client.managed.ui.TimerMobileEditView;
import com.tms.vsc.pcps.test.client.proxy.TimerProxy;
import com.tms.vsc.pcps.test.client.request.TimerRequest;
import com.tms.vsc.pcps.test.client.scaffold.ScaffoldApp;
import com.tms.vsc.pcps.test.client.scaffold.place.CreateAndEditProxy;
import com.tms.vsc.pcps.test.client.scaffold.place.FindAndEditProxy;
import com.tms.vsc.pcps.test.client.scaffold.place.ProxyPlace;

public abstract class TimerActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        TimerEditView.instance().setCreating(true);
        final TimerRequest request = requests.timerRequest();
        Activity activity = new CreateAndEditProxy<TimerProxy>(TimerProxy.class, request, ScaffoldApp.isMobile() ? TimerMobileEditView.instance() : TimerEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(TimerProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new TimerEditActivityWrapper(requests, ScaffoldApp.isMobile() ? TimerMobileEditView.instance() : TimerEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<com.tms.vsc.pcps.test.client.proxy.TimerProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<TimerProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        TimerEditView.instance().setCreating(false);
        EntityProxyId<TimerProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<TimerProxy>(proxyId, requests, ScaffoldApp.isMobile() ? TimerMobileEditView.instance() : TimerEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(TimerProxy proxy) {
                TimerRequest request = requests.timerRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new TimerEditActivityWrapper(requests, ScaffoldApp.isMobile() ? TimerMobileEditView.instance() : TimerEditView.instance(), activity, proxyId);
    }
}
