// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.tms.vsc.pcps.test.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import com.tms.vsc.pcps.test.client.managed.request.ApplicationRequestFactory;
import com.tms.vsc.pcps.test.client.proxy.TimerProxy;
import com.tms.vsc.pcps.test.client.scaffold.ScaffoldMobileApp;
import com.tms.vsc.pcps.test.client.scaffold.activity.IsScaffoldMobileActivity;
import com.tms.vsc.pcps.test.client.scaffold.place.AbstractProxyListActivity;
import com.tms.vsc.pcps.test.client.scaffold.place.ProxyListView;
import java.util.List;

public abstract class TimerListActivity_Roo_Gwt extends AbstractProxyListActivity<TimerProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public TimerListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<com.tms.vsc.pcps.test.client.proxy.TimerProxy> view, Class<com.tms.vsc.pcps.test.client.proxy.TimerProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.timerRequest().countTimers().fire(callback);
    }
}
